version: "3"
services:
  # ... MORE SERVICES ...
  mongo-bi:
    image: ✅{{YourDockerUser}}✅/mongobi
    restart: always
    volumes:
      #- "✅{{YourSchemaPath}}✅:/home/mongobi/schema.drdl" #Uncomment if you have an schema file
      - "✅{{YourConfFolder}}✅/mongosqld.conf:/home/mongobi/mongosqld.conf"
      - "✅{{YourLogFolder}}✅:/logs"
    container_name: "mongo-bi"
    hostname: "mongo-bi"
    ports:
      - "3307:3307"