version: "3"
services:
  # ... MORE SERVICES ...
  mongo-bi:
    image: helisa-mongo-dev-mv-user/mongobi
    restart: always
    volumes:
      #- "✅{{YourSchemaPath}}✅:/home/mongobi/schema.drdl" #Uncomment if you have an schema file
      - "/home/helisa-mongo-dev-mv-user/mongobi/conf/mongosqld.conf:/home/mongobi/mongosqld.conf"
      - "/home/helisa-mongo-dev-mv-user/mongobi/logs:/logs"
    container_name: "mongo-bi"
    hostname: "mongo-bi"
    ports:
      - "3307:3307"